export interface SceneRefs {
    root: cc.Node;
    farMapLayout: cc.Node | null;
    nodeCamera: cc.Node | null;
    bgNodes: cc.Node[];
    heroNode: cc.Node | null;
    flagNode: cc.Node | null;
    sanNode: cc.Node | null;
    heroSpineNode: cc.Node | null;
    bowSpineNode: cc.Node | null;
    shootLineNode: cc.Node | null;
    carBaseNode: cc.Node | null;
    carNode: cc.Node | null;
    wheelNodes: cc.Node[];
    heroProgressBar: cc.ProgressBar | null;
    bossNode: cc.Node | null;
    monsterRoot: cc.Node | null;
    bossProgressBar: cc.ProgressBar | null;
    bossHpLabel: cc.Label | null;
    btnCode: cc.Node | null;
    btnStart: cc.Node | null;
    btnUpLayout: cc.Node | null;
    btnBuyCar: cc.Node | null;
    btnUnlockSkill: cc.Node | null;
    btnUpHurt: cc.Node | null;
    hurtPointNodes: cc.Node[];
    btnUpHp: cc.Node | null;
    hpPointNodes: cc.Node[];
    btnUnlockDef: cc.Node | null;
    btnUpEnergy: cc.Node | null;
    btnBattleLayout: cc.Node | null;
    labelHurt: cc.Label | null;
    labelHp: cc.Label | null;
    labelEnergyRate: cc.Label | null;
    powerBar: cc.ProgressBar | null;
    labelPower: cc.Label | null;
    nodeBattleProgress: cc.Node | null;
    battleBar: cc.ProgressBar | null;
    imgEnergyProgress: cc.ProgressBar | null;
    labelEnergy: cc.Label | null;
    labelBombCost: cc.Label | null;
    labelSawtoothCost: cc.Label | null;
    btnAnswer1: cc.Node | null;
    btnAnswer2: cc.Node | null;
}
